### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by ElanYoung** [condorheroblog/vite-plugin-fake-server#10]
系统环境：Windows 10

版本号：2.0.0

在 Vue3 + Vite 4下，访问Mock接口404，并且控制台显示：`failed to load module from mock\example.js`

![image](https://github.com/condorheroblog/vite-plugin-fake-server/assets/39727435/383d506b-6e33-4ee6-bbb7-be21d75b2345)

vite.config,js 配置如下：

```js
vitePluginFakeServer({
  // 设置模拟数据存储文件夹
  include: 'mock',
  // 中缀名称
  infixName: false,
  // 开发环境环境是否启用
  enableDev: true,
  // 生成环境是否启用
  enableProd: false,
  // 是否在控制台显示请求日志
  logger: true,
}),
```

```js
import { faker } from '@faker-js/faker';

export default [
  {
    url: '/fake/get-user-info',
    response: () => {
      return {
        id: faker.string.uuid(),
        avatar: faker.image.avatar(),
        birthday: faker.date.birthdate(),
        email: faker.internet.email(),
        firstName: faker.person.firstName(),
        lastName: faker.person.lastName(),
        sex: faker.person.sexType(),
        role: 'admin',
      };
    },
  },
];
```

**Comment by condorheroblog** [comment]
目前来看是加载 JS 文件失败了，你可以下载 https://github.com/condorheroblog/vite-plugin-fake-server/tree/main/packages/playground 里面的项目试试能不能运行，加载文件依赖的库是 https://github.com/condorheroblog/bundle-import

2.0.0 版本有人帮我测试过肯定是支持 Windows 系统的，我不确定你的失败是因为啥。

**Comment by ElanYoung** [comment]
> 目前来看是加载 JS 文件失败了，你可以下载 https://github.com/condorheroblog/vite-plugin-fake-server/tree/main/packages/playground 里面的项目试试能不能运行，加载文件依赖的库是 https://github.com/condorheroblog/bundle-import
> 
> 2.0.0 版本有人帮我测试过肯定是支持 Windows 系统的，我不确定你的失败是因为啥。

我试试哈

**Comment by ElanYoung** [comment]
https://github.com/condorheroblog/vite-plugin-fake-server/tree/main/packages/playground/vue-sample 启动报错：

```
X [ERROR] Failed to resolve entry for package "vite-plugin-fake-server". The package may have incorrect main/module/exports specified in its package.json. [plugin externalize-deps]  

    ../../../node_modules/.pnpm/registry.npmmirror.com+esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:27:
      1373 │         let result = await callback({
           ╵                            ^

    at packageEntryFailure (file:///C:/Users/20201216/Desktop/vite-plugin-fake-server-main/node_modules/.pnpm/registry.npmmirror.com+vite@4.5.0_@types+node@20.8.10/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28725:11)
    at resolvePackageEntry (file:///C:/Users/20201216/Desktop/vite-plugin-fake-server-main/node_modules/.pnpm/registry.npmmirror.com+vite@4.5.0_@types+node@20.8.10/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28722:5)
    at tryNodeResolve (file:///C:/Users/20201216/Desktop/vite-plugin-fake-server-main/node_modules/.pnpm/registry.npmmirror.com+vite@4.5.0_@types+node@20.8.10/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28453:20)
    at resolveByViteResolver (file:///C:/Users/20201216/Desktop/vite-plugin-fake-server-main/node_modules/.pnpm/registry.npmmirror.com+vite@4.5.0_@types+node@20.8.10/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66217:32)
    at file:///C:/Users/20201216/Desktop/vite-plugin-fake-server-main/node_modules/.pnpm/registry.npmmirror.com+vite@4.5.0_@types+node@20.8.10/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66258:40
    at requestCallbacks.on-resolve (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:1373:28)
    at handleRequest (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:729:19)       
    at handleIncomingPacket (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:755:7) 
    at Socket.readFromStdout (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:679:7)    at Socket.emit (node:events:517:28)

  This error came from the "onResolve" callback registered here:

    ../../../node_modules/.pnpm/registry.npmmirror.com+esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///C:/Users/20201216/Desktop/vite-plugin-fake-server-main/node_modules/.pnpm/registry.npmmirror.com+vite@4.5.0_@types+node@20.8.10/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66243:27)
    at handlePlugins (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:1292:21)      
    at buildOrContextImpl (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:978:5)   
    at Object.buildOrContext (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:786:5)    at C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:2177:15
    at new Promise (<anonymous>)
    at Object.build (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:2176:25)       
    at build (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:2025:51)
    at bundleConfigFile (file:///C:/Users/20201216/Desktop/vite-plugin-fake-server-main/node_modules/.pnpm/registry.npmmirror.com+vite@4.5.0_@types+node@20.8.10/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66194:26)

  The plugin "externalize-deps" was triggered by this import

    vite.config.ts:4:37:
      4 │ import { vitePluginFakeServer } from "vite-plugin-fake-server";
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from C:\Users\20201216\Desktop\vite-plugin-fake-server-main\packages\playground\vue-sample\vite.config.ts
error when starting dev server:
Error: Build failed with 1 error:
../../../node_modules/.pnpm/registry.npmmirror.com+esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "vite-plugin-fake-server". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:1649:15)    at C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:1058:25
    at runOnEndCallbacks (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:1484:45)  
    at buildResponseToResult (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:1056:7)
    at C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:1085:16        
    at responseCallbacks.<computed> (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:703:9)
    at handleIncomingPacket (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:762:9)
    at Socket.readFromStdout (C:\Users\20201216\Desktop\vite-plugin-fake-server-main\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:679:7)    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:335:12)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by condorheroblog** [comment]
https://github.com/condorheroblog/vite-plugin-fake-server/blob/4860a0da19d06098cad7cb75d1dccc4613f07680/packages/playground/vue-sample/package.json#L18

这里使用了 monorepo 要么整个项目拉取下来使用 pnpm 安装，单独拉取下来需要改成 2.0.0，上面应该是这个问题吧😁

**Comment by ElanYoung** [comment]
> https://github.com/condorheroblog/vite-plugin-fake-server/blob/4860a0da19d06098cad7cb75d1dccc4613f07680/packages/playground/vue-sample/package.json#L18
> 
> 这里使用了 monorepo 要么整个项目拉取下来使用 pnpm 安装，单独拉取下来需要改成 2.0.0，上面应该是这个问题吧😁

还是报上面错误，已经在根目录pnpm安装了

**Comment by condorheroblog** [comment]
1. https://github.com/jsxiaosi/vue-xs-admin
2. https://github.com/pure-admin/vue-pure-admin

你可以在本地直接试试上面两个库，他们都是用了这个插件，但都运行良好😁

**Comment by kayanouriko** [comment]
你需要先在 vite-plugin-fake-server 文件夹执行 pnpm run build 释出 dist 才能启动 playground 里面的 demo.
